import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarCom from "@/components/NavbarCom";
import FooterCom from "@/components/Footer/FooterCom";
import { FriendProvider } from "@/context/FriendContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        suppressHydrationWarning
        className="min-h-full flex flex-col bg-gray-50 dark:bg-gray-700"
      >
        <NavbarCom />
        <FriendProvider>{children}</FriendProvider>
        <Toaster
          reverseOrder={false}
          position="top-right"
          toastOptions={{
            style: {
              top: "0",
              left: "50%",
              transform: "translateX(-50%)",
              background: "#1f2937",
              color: "#fff",
              border: "1px solid #374151",
            },
          }}
        />
        <FooterCom />
      </body>
    </html>
  );
}
